export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image?: string;
  isPopular?: boolean;
  isVegetarian?: boolean;
  isSpicy?: boolean;
}

export interface MenuCategory {
  id: string;
  title: string;
  description: string;
  items: MenuItem[];
}

export const menuData = {
  breakfast: {
    id: "breakfast",
    title: "Breakfast",
    description: "Start your day with our delicious breakfast selections",
    items: [
      {
        id: "br1",
        name: "Kosa Breakfast",
        description: "Two eggs (any style), wheat toast with butter & house-made jam, served with fresh coffee or tea",
        price: 80,
        isPopular: true,
      },
      {
        id: "br2",
        name: "Kosa Breakfast Deluxe",
        description: "Two eggs (any style), wheat toast, fresh coffee or tea, with chicken sausage, tuna, or veggie sausage",
        price: 95,
        isPopular: true,
      },
      {
        id: "br3",
        name: "Vegetable Omelette",
        description: "Fresh vegetables folded into fluffy eggs",
        price: 70,
        isVegetarian: true,
      },
      {
        id: "br4",
        name: "Vegetable Sausage Omelette",
        description: "Omelette with vegetable sausage",
        price: 70,
      },
      {
        id: "br5",
        name: "Cheese Omelette",
        description: "Classic omelette with melted cheese (Add Cheese Ghc20)",
        price: 70,
        isPopular: true,
      },
      {
        id: "br6",
        name: "Tuna Omelette",
        description: "Omelette filled with tuna",
        price: 70,
      },
      {
        id: "br7",
        name: "Ghanaian Pancakes",
        description: "Traditional pancakes served with honey or chocolate",
        price: 45,
      },
      {
        id: "br8",
        name: "Pancakes with Fresh Seasonal Fruits",
        description: "Fluffy pancakes topped with fresh seasonal fruits, served with honey or chocolate",
        price: 70,
        isPopular: true,
      },
      {
        id: "br9",
        name: "Seasonal Fruit Bowl",
        description: "Fresh seasonal fruits artfully arranged",
        price: 80,
        isVegetarian: true,
      },
      {
        id: "br10",
        name: "Oatmeal (Porridge)",
        description: "Warm oatmeal served with fresh milk",
        price: 40,
        isVegetarian: true,
      },
      {
        id: "br11",
        name: "Cornflakes",
        description: "Crispy cornflakes served with fresh milk",
        price: 35,
        isVegetarian: true,
      },
      {
        id: "br12",
        name: "Muesli with Seasonal Fruits",
        description: "A wholesome blend of rolled oats, nuts, and dried fruits topped with fresh seasonal fruits, served with chilled milk",
        price: 60,
        isVegetarian: true,
      },
      {
        id: "br13",
        name: "Egg Sandwich",
        description: "Fresh egg sandwich",
        price: 55,
      },
      {
        id: "br14",
        name: "Tuna Sandwich",
        description: "Tuna sandwich",
        price: 60,
      },
      {
        id: "br15",
        name: "Chicken Sandwich",
        description: "Chicken sandwich",
        price: 60,
      },
      {
        id: "br16",
        name: "Tomato Mozzarella Basil Sandwich",
        description: "Fresh tomato, mozzarella, and basil sandwich",
        price: 65,
        isVegetarian: true,
      },
      {
        id: "br17",
        name: "Wheat Toast with Butter & House-made Jam or Honey",
        description: "Freshly toasted wheat bread with butter and house-made jam or honey",
        price: 40,
        isVegetarian: true,
      },
      {
        id: "br18",
        name: "Chicken Sausage",
        description: "Breakfast extra - chicken sausage",
        price: 15,
      },
      {
        id: "br19",
        name: "Veggie Sausage",
        description: "Breakfast extra - veggie sausage",
        price: 35,
        isVegetarian: true,
      },
      {
        id: "br20",
        name: "Tuna",
        description: "Breakfast extra - tuna",
        price: 35,
      },
    ],
  },
  starters: {
    id: "starters",
    title: "Starters & Appetizers",
    description: "Perfect beginnings to your culinary journey",
    items: [
      {
        id: "st1",
        name: "Fresh Tomato Soup with Toast",
        description: "House-made fresh tomato soup served with toasted bread",
        price: 55,
      },
      {
        id: "st2",
        name: "Vegetable Soup with Toast",
        description: "Fresh vegetable soup served with toasted bread",
        price: 60,
        isVegetarian: true,
      },
      {
        id: "st3",
        name: "Chicken Soup with Toast",
        description: "Hearty chicken soup served with toasted bread",
        price: 65,
      },
      {
        id: "st4",
        name: "Spring Rolls (2 pieces)",
        description: "Crispy spring rolls",
        price: 75,
        isPopular: true,
      },
      {
        id: "st5",
        name: "Kelewele",
        description: "Spicy fried plantain cubes - a Ghanaian favorite",
        price: 50,
        isSpicy: true,
        isPopular: true,
      },
      {
        id: "st6",
        name: "Yam Balls with Sauce",
        description: "Crispy yam balls served with dipping sauce",
        price: 45,
      },
      {
        id: "st7",
        name: "Bruschetta with Fresh Tomatoes (4 pieces)",
        description: "Toasted bread topped with fresh tomatoes and herbs",
        price: 30,
        isVegetarian: true,
      },
      {
        id: "st8",
        name: "Mixed Garden Salad",
        description: "Fresh mixed greens with seasonal vegetables",
        price: 95,
        isVegetarian: true,
      },
      {
        id: "st9",
        name: "Chicken Salad",
        description: "Fresh greens with grilled chicken",
        price: 105,
        isPopular: true,
      },
      {
        id: "st10",
        name: "Beef & Mango Salad",
        description: "Tender beef with fresh mango on mixed greens",
        price: 105,
      },
      {
        id: "st11",
        name: "Chicken Wings",
        description: "Fried or tossed in spicy green or red chili sauce",
        price: 120,
        isSpicy: true,
        isPopular: true,
      },
      {
        id: "st12",
        name: "Chicken Kebab",
        description: "Grilled chicken skewer",
        price: 50,
      },
      {
        id: "st13",
        name: "Fish Kebab",
        description: "Grilled fish skewer",
        price: 55,
      },
      {
        id: "st14",
        name: "Beef Kebab",
        description: "Grilled beef skewer",
        price: 55,
      },
      {
        id: "st15",
        name: "Veggie Kebab",
        description: "Grilled vegetable skewer",
        price: 50,
        isVegetarian: true,
      },
    ],
  },
  mains: {
    id: "mains",
    title: "Main Courses",
    description: "Signature dishes featuring the finest ingredients",
    items: [
      {
        id: "main1",
        name: "Jollof Rice with Chicken (grilled)",
        description: "Traditional West African jollof rice with perfectly grilled chicken",
        price: 140,
        isPopular: true,
      },
      {
        id: "main2",
        name: "Fried Rice with Chicken (grilled)",
        description: "Seasoned fried rice with grilled chicken",
        price: 140,
      },
      {
        id: "main3",
        name: "Red Red with Chicken or Fish",
        description: "Traditional Ghanaian bean stew served with fried plantains and your choice of chicken or fish",
        price: 150,
        isPopular: true,
      },
      {
        id: "main4",
        name: "Mushroom Stroganoff with Plain Rice",
        description: "Creamy mushroom stroganoff served with steamed rice",
        price: 125,
        isVegetarian: true,
      },
      {
        id: "main5",
        name: "Yam with Palava Sauce",
        description: "Boiled yam served with traditional palava sauce",
        price: 80,
        isVegetarian: true,
      },
      {
        id: "main6",
        name: "Chicken Groundnut Soup",
        description: "Rich peanut soup with chicken (Served with plain rice, omatuo rice balls, or banku)",
        price: 140,
        isPopular: true,
      },
      {
        id: "main7",
        name: "Beef Groundnut Soup",
        description: "Rich peanut soup with beef (Served with plain rice, omatuo rice balls, or banku)",
        price: 140,
      },
      {
        id: "main8",
        name: "Red Snapper Groundnut Soup",
        description: "Rich peanut soup with red snapper (Served with plain rice, omatuo rice balls, or banku)",
        price: 140,
      },
      {
        id: "main9",
        name: "Banku with Chicken & Pepper Sauce",
        description: "Fermented corn and cassava dough with grilled chicken and spicy pepper sauce",
        price: 130,
        isSpicy: true,
      },
      {
        id: "main10",
        name: "Banku with Red Snapper & Pepper Sauce",
        description: "Banku with grilled red snapper and spicy pepper sauce",
        price: 130,
        isSpicy: true,
        isPopular: true,
      },
      {
        id: "main11",
        name: "Banku and Okro",
        description: "Banku served with okro soup and your choice of fish, chicken or beef",
        price: 130,
      },
      {
        id: "main12",
        name: "Fufu and Light Soup",
        description: "Traditional fufu with light soup and your choice of fish, chicken or beef",
        price: 80,
      },
      {
        id: "main13",
        name: "Fufu with Chicken Light Soup",
        description: "Fufu with chicken light soup",
        price: 140,
      },
      {
        id: "main14",
        name: "Fufu with Red Snapper Light Soup",
        description: "Fufu with red snapper light soup",
        price: 140,
      },
      {
        id: "main15",
        name: "Fufu with Beef Light Soup",
        description: "Fufu with beef light soup",
        price: 140,
      },
      {
        id: "main16",
        name: "Fisherman's Soup with Red Snapper",
        description: "Rich seafood soup with red snapper (Served with toast, rice or rice balls)",
        price: 140,
        isPopular: true,
      },
      {
        id: "main17",
        name: "Fisherman's Soup with Grouper Fillet",
        description: "Rich seafood soup with grouper fillet (Served with toast, rice or rice balls)",
        price: 140,
      },
      {
        id: "main18",
        name: "Chicken Indian Curry",
        description: "Aromatic Indian-style chicken curry",
        price: 150,
        isSpicy: true,
      },
      {
        id: "main19",
        name: "Chicken with Mushroom Sauce",
        description: "Tender chicken in creamy mushroom sauce (Comes with your choice of a side)",
        price: 150,
      },
      {
        id: "main20",
        name: "Stuffed Chicken Fillet",
        description: "Chicken fillet stuffed with savory filling (Comes with your choice of a side)",
        price: 180,
      },
      {
        id: "main21",
        name: "Sliced Tenderloin Beef with Vegetables",
        description: "Tender beef slices with fresh vegetables (Comes with your choice of a side)",
        price: 160,
      },
      {
        id: "main22",
        name: "Beef Stew",
        description: "Hearty beef stew (Comes with your choice of a side)",
        price: 160,
      },
      {
        id: "main23",
        name: "Steak Dinner with One Side",
        description: "Grilled steak served with your choice of side",
        price: 160,
        isPopular: true,
      },
      {
        id: "main24",
        name: "Meatballs with Tomato Sauce",
        description: "Savory meatballs in rich tomato sauce (Comes with your choice of a side)",
        price: 160,
      },
      {
        id: "main25",
        name: "Beef in Coconut Sauce",
        description: "Tender beef in creamy coconut sauce (Comes with your choice of a side)",
        price: 160,
      },
      {
        id: "main26",
        name: "Spaghetti with Tomato Garlic Sauce",
        description: "Classic spaghetti with tomato garlic sauce",
        price: 75,
        isVegetarian: true,
      },
      {
        id: "main27",
        name: "Vegetable Olive Oil Garlic Pasta",
        description: "Fresh vegetables with olive oil and garlic pasta",
        price: 85,
        isVegetarian: true,
      },
      {
        id: "main28",
        name: "Spicy Delhi Beef Pasta",
        description: "Spicy Indian-style beef pasta",
        price: 100,
        isSpicy: true,
      },
      {
        id: "main29",
        name: "Bolognese",
        description: "Classic spaghetti bolognese",
        price: 110,
        isPopular: true,
      },
      {
        id: "main30",
        name: "Seafood Pasta",
        description: "Pasta with fresh seafood",
        price: 160,
        isPopular: true,
      },
      {
        id: "main31",
        name: "Beef Burger",
        description: "Juicy beef burger served with hand cut fries or yam chips plus coleslaw or side salad",
        price: 110,
        isPopular: true,
      },
      {
        id: "main32",
        name: "Fish Burger",
        description: "Fresh fish burger served with hand cut fries or yam chips plus coleslaw or side salad",
        price: 120,
      },
      {
        id: "main33",
        name: "Chicken Burger",
        description: "Grilled chicken burger served with hand cut fries or yam chips plus coleslaw or side salad",
        price: 120,
        isPopular: true,
      },
      {
        id: "main34",
        name: "Chicken Kebab Plate",
        description: "Chicken kebab with peanut sauce, served with one side of your choice",
        price: 140,
      },
      {
        id: "main35",
        name: "Beef Kebab Plate",
        description: "Beef kebab served with one side of your choice",
        price: 130,
      },
      {
        id: "main36",
        name: "Seafood Kebab Plate",
        description: "Mixed seafood kebab served with one side of your choice",
        price: 145,
      },
      {
        id: "main37",
        name: "Veggie Kebab Plate",
        description: "Grilled vegetable kebab served with one side of your choice",
        price: 105,
        isVegetarian: true,
      },
      {
        id: "main38",
        name: "Prawns Kebab Plate",
        description: "Grilled prawns kebab served with one side of your choice",
        price: 145,
      },
      {
        id: "main39",
        name: "Grilled Squid Kebab Plate",
        description: "Grilled squid kebab served with one side of your choice",
        price: 95,
      },
      {
        id: "main40",
        name: "Whole Red Snapper - Ko-Sa Style",
        description: "Whole red snapper served with sliced vegetables & one side of your choice",
        price: 190,
        isPopular: true,
      },
      {
        id: "main41",
        name: "Grilled or Fried Red Snapper",
        description: "Red snapper grilled or fried to perfection, served with one side of your choice",
        price: 160,
        isPopular: true,
      },
      {
        id: "main42",
        name: "Grilled Lobster or Prawns",
        description: "Fresh grilled lobster or prawns served with one side of your choice",
        price: 280,
      },
      {
        id: "main43",
        name: "Grilled Prawns",
        description: "Succulent grilled prawns served with one side of your choice",
        price: 280,
      },
      {
        id: "main44",
        name: "Steamed Grouper in Coconut & Lemongrass",
        description: "Grouper wrapped in banana leaf, steamed with coconut & lemongrass, served with one side of your choice",
        price: 170,
        isPopular: true,
      },
      {
        id: "main45",
        name: "Grouper Fillet in Mushroom Sauce",
        description: "Tender grouper fillet in creamy mushroom sauce, served with one side of your choice",
        price: 170,
      },
      {
        id: "main46",
        name: "Grouper Fillet in Garlic Butter Sauce",
        description: "Grouper fillet in rich garlic butter sauce, served with one side of your choice",
        price: 170,
      },
      {
        id: "main47",
        name: "Squid in Peri Peri Vegetable Stew",
        description: "Spicy peri peri squid with vegetables, served with one side of your choice",
        price: 170,
        isSpicy: true,
      },
      {
        id: "main48",
        name: "Seafood Platter (Serves up to 3)",
        description: "Lobster, prawns, grouper, squid with two sides of your choice",
        price: 550,
        isPopular: true,
      },
      {
        id: "main49",
        name: "Chicken Sandwich",
        description: "Chicken sandwich served with fries or yam chips plus coleslaw or side salad",
        price: 110,
      },
      {
        id: "main50",
        name: "Tuna Sandwich",
        description: "Tuna sandwich served with fries or yam chips plus coleslaw or side salad",
        price: 110,
      },
      {
        id: "main51",
        name: "Tomato Mozzarella Basil Sandwich",
        description: "Fresh tomato, mozzarella and basil sandwich served with fries or yam chips plus coleslaw or side salad",
        price: 115,
        isVegetarian: true,
      },
      {
        id: "main52",
        name: "Club Sandwich",
        description: "Classic club sandwich served with fries or yam chips plus coleslaw or side salad",
        price: 120,
      },
      {
        id: "main53",
        name: "Fried Rice",
        description: "Seasoned fried rice side dish",
        price: 50,
      },
      {
        id: "main54",
        name: "Jollof Rice",
        description: "Traditional jollof rice side dish",
        price: 50,
      },
      {
        id: "main55",
        name: "Plain Rice",
        description: "Steamed white rice",
        price: 50,
      },
      {
        id: "main56",
        name: "Mashed Potato",
        description: "Creamy mashed potatoes",
        price: 80,
      },
      {
        id: "main57",
        name: "Sautéed Potato",
        description: "Sautéed potatoes with herbs",
        price: 80,
      },
      {
        id: "main58",
        name: "Hand Cut Fries",
        description: "Fresh hand-cut french fries",
        price: 60,
      },
      {
        id: "main59",
        name: "Fried Plantain",
        description: "Sweet fried plantain",
        price: 65,
      },
      {
        id: "main60",
        name: "Coastal Coleslaw",
        description: "Fresh coleslaw",
        price: 50,
      },
      {
        id: "main61",
        name: "Yam Chips",
        description: "Crispy yam chips",
        price: 50,
      },
    ],
  },
  children: {
    id: "children",
    title: "Children's Menu",
    description: "Delicious and nutritious meals for our little guests",
    items: [
      {
        id: "kid1",
        name: "Fish Basket with Fries",
        description: "Crispy fish basket served with fries",
        price: 100,
        isPopular: true,
      },
      {
        id: "kid2",
        name: "Chicken Basket with Fries",
        description: "Golden chicken basket served with fries",
        price: 80,
        isPopular: true,
      },
      {
        id: "kid3",
        name: "Spaghetti with Meatballs",
        description: "Kid-friendly spaghetti with meatballs",
        price: 75,
      },
      {
        id: "kid4",
        name: "Spaghetti with Beef Sauce",
        description: "Spaghetti with mild beef sauce",
        price: 70,
      },
    ],
  },
  desserts: {
    id: "desserts",
    title: "Desserts",
    description: "Sweet endings to complete your dining experience",
    items: [
      {
        id: "des1",
        name: "Auntie Bene's Cookies",
        description: "House-made cookies",
        price: 40,
        isPopular: true,
      },
      {
        id: "des2",
        name: "Auntie Bene's Cake",
        description: "Delicious house-made cake",
        price: 50,
        isPopular: true,
      },
      {
        id: "des3",
        name: "Ice Cream",
        description: "Creamy ice cream",
        price: 15,
      },
      {
        id: "des4",
        name: "Ice Cream Chocolate Sauce",
        description: "Ice cream drizzled with chocolate sauce",
        price: 20,
      },
      {
        id: "des5",
        name: "Fried Banana with Chocolate Sauce",
        description: "Sweet fried banana with chocolate sauce",
        price: 30,
      },
      {
        id: "des6",
        name: "Fried Banana with Ice Cream & Chocolate Sauce",
        description: "Fried banana topped with ice cream and chocolate sauce",
        price: 40,
        isPopular: true,
      },
      {
        id: "des7",
        name: "Crepe (Cinnamon and Brown Sugar)",
        description: "Delicate crepe with cinnamon and brown sugar",
        price: 45,
      },
      {
        id: "des8",
        name: "Crepe with Seasonal Fruits",
        description: "Crepe topped with fresh seasonal fruits",
        price: 60,
        isPopular: true,
      },
      {
        id: "des9",
        name: "Crepe with Ice Cream",
        description: "Crepe served with ice cream",
        price: 60,
      },
      {
        id: "des10",
        name: "Banana Milkshake",
        description: "Thick and creamy banana milkshake",
        price: 65,
      },
    ],
  },
  drinks: {
    id: "drinks",
    title: "Beverages",
    description: "Refreshing drinks to complement your meal",
    items: [
      {
        id: "drk1",
        name: "African Hibiscus Juice (Bissap)",
        description: "House-made hibiscus juice",
        price: 35,
        isPopular: true,
      },
      {
        id: "drk2",
        name: "Fresh Orange Juice",
        description: "Freshly squeezed orange juice",
        price: 35,
        isPopular: true,
      },
      {
        id: "drk3",
        name: "Fresh Pineapple Juice",
        description: "Freshly squeezed pineapple juice",
        price: 35,
      },
      {
        id: "drk4",
        name: "Mixed Fruit Juice",
        description: "Blend of fresh tropical fruits",
        price: 40,
      },
      {
        id: "drk5",
        name: "Banana Milkshake",
        description: "Thick and creamy banana milkshake",
        price: 65,
      },
      {
        id: "drk6",
        name: "Smoothie (Seasonal)",
        description: "Fresh seasonal fruit smoothie",
        price: 65,
        isPopular: true,
      },
      {
        id: "drk7",
        name: "Mineral Water Small (750ml)",
        description: "Bottled mineral water",
        price: 10,
      },
      {
        id: "drk8",
        name: "Mineral Water Large (1.5L)",
        description: "Large bottle mineral water",
        price: 15,
      },
      {
        id: "drk9",
        name: "Green/Black Tea",
        description: "Selection of premium teas",
        price: 20,
      },
      {
        id: "drk10",
        name: "Glass Milk",
        description: "Fresh cold milk",
        price: 20,
      },
      {
        id: "drk11",
        name: "Hot Chocolate",
        description: "Rich hot chocolate",
        price: 20,
      },
      {
        id: "drk12",
        name: "Fresh Coffee or Espresso",
        description: "Freshly brewed coffee or espresso",
        price: 25,
        isPopular: true,
      },
      {
        id: "drk13",
        name: "Cappuccino",
        description: "Classic Italian cappuccino",
        price: 35,
      },
      {
        id: "drk14",
        name: "Caffè Latte",
        description: "Smooth caffè latte",
        price: 35,
      },
      {
        id: "drk15",
        name: "Latte Macchiato",
        description: "Layered latte macchiato",
        price: 35,
      },
      {
        id: "drk16",
        name: "Ice Coffee",
        description: "Refreshing iced coffee",
        price: 35,
      },
    ],
  },
  wines: {
    id: "wines",
    title: "Wine & Spirits Selection",
    description: "Carefully curated wines and spirits",
    items: [
      {
        id: "wine1",
        name: "4th Street Wine",
        description: "Sweet and fruity wine (750ml)",
        price: 120,
        isPopular: true,
      },
      {
        id: "wine2",
        name: "Viceroy Brandy",
        description: "Premium brandy (750ml)",
        price: 180,
      },
      {
        id: "wine3",
        name: "Dry Gin",
        description: "Classic dry gin - single shot",
        price: 25,
      },
      {
        id: "wine4",
        name: "Gordon's Dry Gin",
        description: "Premium London dry gin (750ml)",
        price: 180,
        isPopular: true,
      },
    ],
  },
};